name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: env
        run: env
      - name: test curl
        run: curl -I -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' --url https://api.github.com/user
